---
- name: webservices
  user: root
  hosts: webservices
  plugins:
    - name: systemd
      service_name: "webservice@*"
    - name: webservice
      request_from_server: true
      routes:
        method: GET
        route: "http://{{ webservice_url }}/api/status"
        host: localhost
        port: 800x
